/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mtn_app;
import javax.swing.*;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.Objects;


/**
 *
 * @author jerrito
 */
public class Recipient_details extends javax.swing.JFrame {

    /**
     * Creates new form Recipient_details
     */
    public Recipient_details() {
        initComponents();

    }
    Connection con=null;
    ResultSet rs=null;
    Statement st=null;
    PreparedStatement preparedStatement=null;
    Homes h=new Homes();
    Momo m=new Momo();
    Airtime_complete A_c=new Airtime_complete();
    Confirm C =new Confirm();
    public String credit;
    public Float Bundle;
    public  Float amount;
    double price=0.0;
    Float x;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        homes2 = new javax.swing.JLabel();
        align = new javax.swing.JLabel();
        mtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        momo = new javax.swing.JRadioButton();
        Airtime = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        wrong_num = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        decider = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        momo_button = new javax.swing.JButton();
        air = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        credit_others = new javax.swing.JLabel();
        bundle_amount = new javax.swing.JLabel();
        bundle_data = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        proceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1373, 786));
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(1373, 82));
        jPanel6.setMinimumSize(new java.awt.Dimension(1373, 82));
        jPanel6.setPreferredSize(new java.awt.Dimension(1373, 82));

        homes2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homes2.setText("Recipient");

        align.setIcon(new javax.swing.ImageIcon("C:\\Users\\jerrito\\Documents\\NetBeansProjects\\mtn\\src\\main\\java\\com\\mycompany\\favicon_io\\centered-justification.png")); // NOI18N
        align.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alignMouseClicked(evt);
            }
        });

        mtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\jerrito\\Documents\\NetBeansProjects\\MTN_APP\\favicon_io\\undo.png")); // NOI18N
        mtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(mtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406)
                .addComponent(homes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(align)
                .addGap(88, 88, 88))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(align, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homes2))
                .addGap(10, 10, 10))
        );

        jPanel5.setMaximumSize(new java.awt.Dimension(1373, 517));
        jPanel5.setMinimumSize(new java.awt.Dimension(1373, 517));
        jPanel5.setPreferredSize(new java.awt.Dimension(1373, 517));

        buttonGroup1.add(momo);
        momo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        momo.setSelected(true);
        momo.setText("MoMo");
        momo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        momo.setBorderPainted(true);
        momo.setIconTextGap(10);
        momo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                momoActionPerformed(evt);
            }
        });

        buttonGroup1.add(Airtime);
        Airtime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Airtime.setText("Airtime");
        Airtime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Airtime.setBorderPainted(true);
        Airtime.setIconTextGap(10);
        Airtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirtimeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter amount");

        wrong_num.setForeground(new java.awt.Color(255, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1373, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(1373, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(1373, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Sending airtime to");

        number.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        number.setForeground(new java.awt.Color(0, 153, 153));

        decider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        decider.setForeground(new java.awt.Color(255, 255, 255));
        decider.setText("w");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(629, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(573, 573, 573)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decider)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(decider))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Payment Method");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("MoMo Balance:");

        momo_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        momo_button.setForeground(new java.awt.Color(0, 153, 153));
        momo_button.setText("Check MoMo Balance");
        momo_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        momo_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                momo_buttonMouseClicked(evt);
            }
        });

        air.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        air.setForeground(new java.awt.Color(0, 102, 102));

        num.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));

        credit_others.setPreferredSize(new java.awt.Dimension(30, 20));

        bundle_amount.setForeground(new java.awt.Color(255, 255, 255));
        bundle_amount.setText("0");

        bundle_data.setForeground(new java.awt.Color(255, 255, 255));
        bundle_data.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1441, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(credit_others, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(air, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(momo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Airtime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(momo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1556, 1556, 1556)
                                .addComponent(wrong_num, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bundle_amount)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bundle_data)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(wrong_num, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credit_others, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(momo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Airtime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(momo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(air, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bundle_amount)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bundle_data)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1373, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(1373, 100));

        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setText("Back");
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        proceed.setBackground(new java.awt.Color(0, 102, 102));
        proceed.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        proceed.setForeground(new java.awt.Color(255, 255, 255));
        proceed.setText("Continue");
        proceed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Fields



    //Gui Code Here

    public double calculate(Float amount){

        if(amount > 0.03 && amount<399.0){
            if(amount<=1.0){
                price=  (amount*48.10);
            }
            else if(amount>1.0 && amount<3.0){
                price=   (amount*48.10)+24.0;
            }
            else if(amount>=3.0 && amount<5){
                price=   (amount*48.10)+327.0;
            }
            else if(amount>=5.0 && amount<10){
                price=   (amount*48.10)+364.0;
            }
            else if(amount>=10.0){
                price=   (amount*48.10)+490.82;
            }
        }
        DecimalFormat df=new DecimalFormat();
        df.setMaximumFractionDigits(2);
        System.out.println(df.format(price)+"MB");

        return price;
    }
    private void alignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alignMouseClicked
        new Settings().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alignMouseClicked

    private void mtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtnMouseClicked
        new Buy_Send().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mtnMouseClicked

    private void momoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_momoActionPerformed
        jLabel1.setText("MoMo Balance:");
        momo_button.setVisible(true);
        air.setVisible(false);
        //calculate(4.000);
    }//GEN-LAST:event_momoActionPerformed

    private void AirtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirtimeActionPerformed
     jLabel1.setText("Airtime Balance:");
     momo_button.setVisible(false);
     air.setText(String.valueOf(h.credits));
     air.setVisible(true);
    }//GEN-LAST:event_AirtimeActionPerformed

    private void proceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedMouseClicked

        DecimalFormat d=new DecimalFormat();
        d.setMaximumFractionDigits(2);

        // for self credit
        if(Objects.equals( decider.getText(),"1")) {

            if (momo.isSelected()) {
                if (Objects.equals(num.getText(), "")) {
                    num.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

                } else {
                    C.jLabel4.setText(credit_others.getText());
                    C.numb.setText(number.getText());
                    C.decider.setText(decider.getText());
                    C.amount.setText(num.getText());
                    C.setVisible(true);
                    this.setVisible(false);
                }
            } else if (Airtime.isSelected()) {
                if (Float.parseFloat(num.getText()) > h.credits) {
                    A_c.id.setText("Service failure");
                    A_c.id.setIcon(new javax.swing.ImageIcon("C:\\Users\\jerrito\\Documents\\NetBeansProjects\\mtn\\src\\main\\java\\com\\mycompany\\favicon_io\\error.png")); // NOI18N
                    A_c.info.setText("Entered amount exceeds your Airtime balance, please enter a lesser amount");
                    A_c.proceed.setVisible(false);
                    A_c.setVisible(true);
                    this.setVisible(false);
                } else {
                    String s = "jdbc:sqlite:C:/Users/jerrito/Documents/NetBeansProjects/MTN_APP/momo.db";
                    try {
                        Class.forName("org.sqlite.JDBC");
                        con = DriverManager.getConnection(s);
                        con.setAutoCommit(false);
                        st = con.createStatement();

                        float airtime_update = Float.parseFloat(credit_others.getText()) + Float.parseFloat(num.getText());
                        System.out.println("thier credit is "+credit_others.getText());
                        st.executeUpdate("Update Momo set Airtime=" + d.format(airtime_update) + " Where number=" + number.getText());
                        con.commit();

                        float airtime_update2 = h.credits - Float.parseFloat(num.getText());
                        st.executeUpdate("Update Momo set Airtime=" + d.format(airtime_update2) + " Where number=" + h.number);
                        con.commit();
                        A_c.info.setText("You have successfully transferred airtime of GH₵" + num.getText() + " to " + number.getText());
                        A_c.setVisible(true);
                        this.setVisible(false);
                        con.close();
                    } catch (SQLException | ClassNotFoundException e) {
                        JOptionPane.showMessageDialog(this, "Network error.\n Please try again");
                        e.printStackTrace();
                    }}}}

        //for data input amount
        else if(Objects.equals(decider.getText(),"2")){
            calculate(Float.parseFloat(num.getText()));
            if (momo.isSelected()){
                if (Objects.equals(num.getText(), "")) {
                    num.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                }
                else{
                    C.decider.setText(decider.getText());
                    C.prices.setText("GH₵ "+num.getText());
                    C.amount.setText(d.format(price )+ "MB");
                    C.numb.setText(number.getText());
                    C.id.setText("Confirm Details");
                    C.priced.setText(d.format(calculate(Float.parseFloat(num.getText()))));
                    C.jLabel10.setVisible(false);
                    C.mb.setText(num.getText());
                    C.setVisible(true);
                    this.dispose();
                    }}
            else if (Airtime.isSelected()){
                if(Float.parseFloat(num.getText())>h.credits){
                    JOptionPane.showMessageDialog(this,"You do not have enough Airtime to purchase this offer. Please recharge and try again");
                }
                else {
                    String s = "jdbc:sqlite:C:/Users/jerrito/Documents/NetBeansProjects/MTN_APP/momo.db";
                    try {
                        Class.forName("org.sqlite.JDBC");
                        con = DriverManager.getConnection(s);
                        con.setAutoCommit(false);
                        st = con.createStatement();
                        float data_update = (float) (Bundle + price);
                        st.executeUpdate("Update Momo set Bundle=" + (data_update) + " Where number=" + number.getText());
                        con.commit();
                        float airtime_update2 = h.credits - Float.parseFloat(num.getText());
                        st.executeUpdate("Update Momo set Airtime=" + d.format(airtime_update2) + " Where number=" + h.number);
                        con.commit();
                        A_c.id.setText("Data successfully sent");
                        A_c.info.setText("You have successfully transferred data of GH₵" + num.getText() + " to " + number.getText());
                        A_c.setVisible(true);
                        this.setVisible(false);
                        con.close();
                    } catch (SQLException | ClassNotFoundException e) {
                        JOptionPane.showMessageDialog(this, "Network error.\n Please try again");
                        e.printStackTrace();
                    }}
            }
        }
        //momo bundle 24mb or 48mb or 471mb or 971mb
        else if(Objects.equals( decider.getText(),"3")||Objects.equals( decider.getText(),"5")||Objects.equals(decider.getText(),"4")||Objects.equals(decider.getText(),"10")){
           if (momo.isSelected()){
             momo_select();}
           else if(Airtime.isSelected()){
           airtime_select();}}




    }//GEN-LAST:event_proceedMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void momo_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_momo_buttonMouseClicked
        JOptionPane.showMessageDialog(this,""+m.balance_main);
    }//GEN-LAST:event_momo_buttonMouseClicked

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        try {
            x = Float.parseFloat(num.getText());
        } catch (NumberFormatException nfe) {
            num.setText("");
        }
    }//GEN-LAST:event_numKeyTyped

    private void numKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyReleased
           try {
            x = Float.parseFloat(num.getText());
        } catch (NumberFormatException nfe) {
            num.setText("");
        }
    }//GEN-LAST:event_numKeyReleased
    public void momo_select(){
        C.numb.setText(number.getText());
        C.decider.setText(decider.getText());
        C.prices.setText(jLabel5.getText());
        C.amount.setText(jLabel2.getText());
        C.id.setText("Confirm Details");
        C.priced.setText(bundle_data.getText());
        System.out.println(bundle_amount.getText());
        C.jLabel10.setVisible(false);
        C.mb.setText(bundle_amount.getText());
        C.setVisible(true);
        this.dispose();
    }
    public void airtime_select(){
        calculate(Float.valueOf(bundle_amount.getText()));
        if(Float.parseFloat(bundle_amount.getText()) > h.credits){
            JOptionPane.showMessageDialog(this,"You do not have enough Airtime to purchase this offer. Please recharge and try again");
        }
        else {
            String s = "jdbc:sqlite:C:/Users/jerrito/Documents/NetBeansProjects/MTN_APP/momo.db";
            try {
                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection(s);
                con.setAutoCommit(false);
                st = con.createStatement();
                float data_update = (float) (Bundle + price);
                st.executeUpdate("Update Momo set Bundle=" + (data_update) + " Where number=" + number.getText());
                con.commit();
                float airtime_update2 = h.credits - Float.parseFloat(bundle_amount.getText());
                st.executeUpdate("Update Momo set Airtime=" + (airtime_update2) + " Where number=" + h.number);
                con.commit();
                A_c.id.setText("Data successfully sent");
                A_c.info.setText("You have successfully transferred data of GH₵" + num.getText() + " to " + number.getText());
                A_c.setVisible(true);
                this.setVisible(false);
                con.close();
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Network error.\n Please try again");
                e.printStackTrace();
            }}
    }
    private void numKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recipient_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recipient_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recipient_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recipient_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recipient_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Airtime;
    public javax.swing.JLabel air;
    private javax.swing.JLabel align;
    public javax.swing.JButton back;
    public javax.swing.JLabel bundle_amount;
    public javax.swing.JLabel bundle_data;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel credit_others;
    public javax.swing.JLabel decider;
    public javax.swing.JLabel homes2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton momo;
    private javax.swing.JButton momo_button;
    private javax.swing.JLabel mtn;
    public javax.swing.JTextField num;
    public javax.swing.JLabel number;
    public javax.swing.JButton proceed;
    private javax.swing.JLabel wrong_num;
    // End of variables declaration//GEN-END:variables
}
